set(TCMALLOC_HEADERS
  tcmalloc/tcmalloc/allocation_sample.h
  tcmalloc/tcmalloc/allocation_sampling.h
  tcmalloc/tcmalloc/arena.h
  tcmalloc/tcmalloc/central_freelist.h
  tcmalloc/tcmalloc/common.h
  tcmalloc/tcmalloc/cpu_cache.h
  tcmalloc/tcmalloc/deallocation_profiler.h
  tcmalloc/tcmalloc/experiment.h
  tcmalloc/tcmalloc/experiment_config.h
  tcmalloc/tcmalloc/global_stats.h
  tcmalloc/tcmalloc/guarded_allocations.h
  tcmalloc/tcmalloc/guarded_page_allocator.h
  tcmalloc/tcmalloc/hinted_tracker_lists.h
  tcmalloc/tcmalloc/huge_address_map.h
  tcmalloc/tcmalloc/huge_allocator.h
  tcmalloc/tcmalloc/huge_cache.h
  tcmalloc/tcmalloc/huge_page_aware_allocator.h
  tcmalloc/tcmalloc/huge_page_filler.h
  tcmalloc/tcmalloc/huge_page_subrelease.h
  tcmalloc/tcmalloc/huge_pages.h
  tcmalloc/tcmalloc/huge_region.h
  tcmalloc/tcmalloc/internal_malloc_extension.h
  tcmalloc/tcmalloc/internal_malloc_tracing_extension.h
  tcmalloc/tcmalloc/libc_override.h
  tcmalloc/tcmalloc/malloc_extension.h
  tcmalloc/tcmalloc/malloc_tracing_extension.h
  tcmalloc/tcmalloc/metadata_allocator.h
  tcmalloc/tcmalloc/new_extension.h
  tcmalloc/tcmalloc/page_allocator.h
  tcmalloc/tcmalloc/page_allocator_interface.h
  tcmalloc/tcmalloc/page_heap.h
  tcmalloc/tcmalloc/page_heap_allocator.h
  tcmalloc/tcmalloc/pagemap.h
  tcmalloc/tcmalloc/pages.h
  tcmalloc/tcmalloc/parameters.h
  tcmalloc/tcmalloc/peak_heap_tracker.h
  tcmalloc/tcmalloc/sampled_allocation_allocator.h
  tcmalloc/tcmalloc/sampler.h
  tcmalloc/tcmalloc/segv_handler.h
  tcmalloc/tcmalloc/size_class_info.h
  tcmalloc/tcmalloc/sizemap.h
  tcmalloc/tcmalloc/span.h
  tcmalloc/tcmalloc/span_stats.h
  tcmalloc/tcmalloc/stack_trace_table.h
  tcmalloc/tcmalloc/static_vars.h
  tcmalloc/tcmalloc/stats.h
  tcmalloc/tcmalloc/system-alloc.h
  tcmalloc/tcmalloc/tcmalloc.h
  tcmalloc/tcmalloc/tcmalloc_policy.h
  tcmalloc/tcmalloc/thread_cache.h
  tcmalloc/tcmalloc/transfer_cache.h
  tcmalloc/tcmalloc/transfer_cache_internals.h
  tcmalloc/tcmalloc/transfer_cache_stats.h
  tcmalloc/tcmalloc/internal/allocation_guard.h
  tcmalloc/tcmalloc/internal/atomic_danger.h
  tcmalloc/tcmalloc/internal/atomic_stats_counter.h
  tcmalloc/tcmalloc/internal/cache_topology.h
  tcmalloc/tcmalloc/internal/clock.h
  tcmalloc/tcmalloc/internal/config.h
  tcmalloc/tcmalloc/internal/declarations.h
  tcmalloc/tcmalloc/internal/environment.h
  tcmalloc/tcmalloc/internal/explicitly_constructed.h
  tcmalloc/tcmalloc/internal/exponential_biased.h
  tcmalloc/tcmalloc/internal/linked_list.h
  tcmalloc/tcmalloc/internal/linux_syscall_support.h
  tcmalloc/tcmalloc/internal/logging.h
  tcmalloc/tcmalloc/internal/memory_stats.h
  tcmalloc/tcmalloc/internal/mincore.h
  tcmalloc/tcmalloc/internal/numa.h
  tcmalloc/tcmalloc/internal/optimization.h
  tcmalloc/tcmalloc/internal/overflow.h
  tcmalloc/tcmalloc/internal/page_size.h
  tcmalloc/tcmalloc/internal/percpu.h
  tcmalloc/tcmalloc/internal/percpu_tcmalloc.h
  tcmalloc/tcmalloc/internal/prefetch
  tcmalloc/tcmalloc/internal/prefetch.h
  tcmalloc/tcmalloc/internal/range_tracker.h
  tcmalloc/tcmalloc/internal/sampled_allocation.h
  tcmalloc/tcmalloc/internal/sampled_allocation_recorder.h
  tcmalloc/tcmalloc/internal/stacktrace_filter.h
  tcmalloc/tcmalloc/internal/sysinfo.h
  tcmalloc/tcmalloc/internal/timeseries_tracker.h
  tcmalloc/tcmalloc/internal/util.h
  tcmalloc/tcmalloc/selsan/selsan.h
)

set(TCMALLOC_SOURCES
  tcmalloc/tcmalloc/allocation_sample.cc
  tcmalloc/tcmalloc/allocation_sampling.cc
  tcmalloc/tcmalloc/arena.cc
  tcmalloc/tcmalloc/background.cc
  tcmalloc/tcmalloc/central_freelist.cc
  tcmalloc/tcmalloc/common.cc
  tcmalloc/tcmalloc/deallocation_profiler.cc
  tcmalloc/tcmalloc/experiment.cc
  tcmalloc/tcmalloc/experimental_pow2_size_class.cc
  tcmalloc/tcmalloc/fewer_size_classes.cc
  tcmalloc/tcmalloc/global_stats.cc
  tcmalloc/tcmalloc/guarded_page_allocator.cc
  tcmalloc/tcmalloc/legacy_size_classes.cc
  tcmalloc/tcmalloc/lowfrag_size_classes.cc
  tcmalloc/tcmalloc/malloc_extension.cc
  tcmalloc/tcmalloc/malloc_tracing_extension.cc
  tcmalloc/tcmalloc/new_extension.cc
  tcmalloc/tcmalloc/page_allocator.cc
  tcmalloc/tcmalloc/transfer_cache.cc
  tcmalloc/tcmalloc/page_allocator_interface.cc
  tcmalloc/tcmalloc/peak_heap_tracker.cc
  tcmalloc/tcmalloc/pagemap.cc
  tcmalloc/tcmalloc/parameters.cc
  tcmalloc/tcmalloc/sampler.cc
  tcmalloc/tcmalloc/thread_cache.cc
  tcmalloc/tcmalloc/size_classes.cc
  tcmalloc/tcmalloc/sizemap.cc
  tcmalloc/tcmalloc/span.cc
  tcmalloc/tcmalloc/stack_trace_table.cc
  tcmalloc/tcmalloc/static_vars.cc
  tcmalloc/tcmalloc/stats.cc
  tcmalloc/tcmalloc/huge_page_aware_allocator.cc
  tcmalloc/tcmalloc/huge_cache.cc
  tcmalloc/tcmalloc/huge_allocator.cc
  tcmalloc/tcmalloc/huge_address_map.cc
  tcmalloc/tcmalloc/system-alloc.cc
  tcmalloc/tcmalloc/tcmalloc.cc
  tcmalloc/tcmalloc/profile_marshaler.cc
  tcmalloc/tcmalloc/internal/profile_builder.cc
  tcmalloc/tcmalloc/internal/cache_topology.cc
  tcmalloc/tcmalloc/internal/allocation_guard.cc
  tcmalloc/tcmalloc/internal/pageflags.cc
  tcmalloc/tcmalloc/internal/residency.cc
  tcmalloc/tcmalloc/internal/environment.cc
  tcmalloc/tcmalloc/internal/logging.cc
  tcmalloc/tcmalloc/internal/memory_stats.cc
  tcmalloc/tcmalloc/internal/mincore.cc
  tcmalloc/tcmalloc/internal/numa.cc
  tcmalloc/tcmalloc/internal/page_size.cc
  tcmalloc/tcmalloc/internal/percpu.cc
  tcmalloc/tcmalloc/internal/percpu_rseq_unsupported.cc
  tcmalloc/tcmalloc/internal/percpu_tcmalloc.cc
  tcmalloc/tcmalloc/internal/sysinfo.cc
  tcmalloc/tcmalloc/internal/util.cc
  tcmalloc/tcmalloc/internal/profile.pb.cc
  tcmalloc/tcmalloc/selsan/selsan.cc
  tcmalloc/tcmalloc/internal/percpu_rseq_asm.S
)

add_library(tcmalloc ${TCMALLOC_SOURCES})

target_include_directories(tcmalloc PUBLIC tcmalloc)
target_link_libraries(tcmalloc PUBLIC absl::base absl::status absl::statusor)
target_link_libraries(tcmalloc PUBLIC protobuf)

add_library(tcmalloc::tcmalloc ALIAS tcmalloc)
