load("//bazel:build.bzl", "redpanda_cc_library")

package(default_visibility = ["//src/v/lsm:__subpackages__"])

redpanda_cc_library(
    name = "exceptions",
    hdrs = ["exceptions.h"],
    deps = ["@fmt"],
)
